In [197]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [198]:
car_data = pd.read_csv('/content/cardekho_dataset.csv')

In [199]:
car_data.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [200]:
car_data.shape

(15411, 14)

In [201]:
car_data.tail()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
15406,19537,Hyundai i10,Hyundai,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5,250000
15407,19540,Maruti Ertiga,Maruti,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7,925000
15408,19541,Skoda Rapid,Skoda,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5,425000
15409,19542,Mahindra XUV500,Mahindra,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7,1225000
15410,19543,Honda City,Honda,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5,1200000

In [202]:
car_data.isnull().sum()

Unnamed: 0           0
car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [203]:
print(car_data.brand.value_counts())
print(car_data.seller_type.value_counts())
print(car_data.fuel_type.value_counts())
print(car_data.transmission_type.value_counts())
print(car_data.model.value_counts())

brand
Maruti           4992
Hyundai          2982
Honda            1485
Mahindra         1011
Toyota            793
Ford              790
Volkswagen        620
Renault           536
BMW               439
Tata              430
Mercedes-Benz     337
Skoda             334
Audi              192
Datsun            170
Jaguar             59
Land Rover         51
Jeep               41
Kia                32
Porsche            21
Volvo              20
MG                 19
Mini               17
Nissan             11
Lexus              10
Isuzu               8
Bentley             3
Maserati            2
ISUZU               2
Ferrari             1
Mercedes-AMG        1
Rolls-Royce         1
Force               1
Name: count, dtype: int64
seller_type
Dealer              9539
Individual          5699
Trustmark Dealer     173
Name: count, dtype: int64
fuel_type
Petrol      7643
Diesel      7419
CNG          301
LPG           44
Electric       4
Name: count, dtype: int64
transmission_type
Manual       12225
Automatic     3186
Name: count, dtype: int64
model
i20             906
Swift Dzire     890
Swift           781
Alto            778
City            757
               ...
Altroz            1
C                 1
Ghost             1
Quattroporte      1
Gurkha            1
Name: count, Length: 120, dtype: int64

**Encoding Manually**

In [204]:
#encoding fuel_type
car_data.replace({'fuel_type':{'Petrol':0,'Diesel':1,'CNG':2,'LPG':3,'Electric':4}},inplace=True)

#encoding seller type
car_data.replace({'seller_type':{'Dealer':0,'Individual':1,'Trustmark Dealer':2}},inplace=True)

#encoding Transmission type
car_data.replace({'transmission_type':{'Manual':0,'Automatic':1}},inplace=True)

In [205]:
car_data.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,1,0,0,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,1,0,0,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,1,0,0,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,1,0,0,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,0,1,0,22.77,1498,98.59,5,570000

In [206]:
car_data.tail()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
15406,19537,Hyundai i10,Hyundai,i10,9,10723,0,0,0,19.81,1086,68.05,5,250000
15407,19540,Maruti Ertiga,Maruti,Ertiga,2,18000,0,0,0,17.50,1373,91.10,7,925000
15408,19541,Skoda Rapid,Skoda,Rapid,6,67000,0,1,0,21.14,1498,103.52,5,425000
15409,19542,Mahindra XUV500,Mahindra,XUV500,5,3800000,0,1,0,16.00,2179,140.00,7,1225000
15410,19543,Honda City,Honda,City,2,13000,0,0,1,18.00,1497,117.60,5,1200000

**Splitting the Data**

In [207]:
car_data = car_data.drop(columns=['Unnamed: 0','car_name','brand','model'])

In [208]:
car_data.head()

,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,9,120000,1,0,0,19.70,796,46.30,5,120000
1,5,20000,1,0,0,18.90,1197,82.00,5,550000
2,11,60000,1,0,0,17.00,1197,80.00,5,215000
3,9,37000,1,0,0,20.92,998,67.10,5,226000
4,6,30000,0,1,0,22.77,1498,98.59,5,570000

In [209]:
X = car_data.drop(columns=['selling_price'])

In [210]:
print(X)

       vehicle_age  km_driven  seller_type  fuel_type  transmission_type  \
0                9     120000            1          0                  0
1                5      20000            1          0                  0
2               11      60000            1          0                  0
3                9      37000            1          0                  0
4                6      30000            0          1                  0
...            ...        ...          ...        ...                ...
15406            9      10723            0          0                  0
15407            2      18000            0          0                  0
15408            6      67000            0          1                  0
15409            5    3800000            0          1                  0
15410            2      13000            0          0                  1

       mileage  engine  max_power  seats
0        19.70     796      46.30      5
1        18.90    1197      82.00      5
2        17.00    1197      80.00      5
3        20.92     998      67.10      5
4        22.77    1498      98.59      5
...        ...     ...        ...    ...
15406    19.81    1086      68.05      5
15407    17.50    1373      91.10      7
15408    21.14    1498     103.52      5
15409    16.00    2179     140.00      7
15410    18.00    1497     117.60      5

[15411 rows x 9 columns]

In [211]:
Y = car_data['selling_price']

In [212]:
print(Y)

0         120000
1         550000
2         215000
3         226000
4         570000
          ...
15406     250000
15407     925000
15408     425000
15409    1225000
15410    1200000
Name: selling_price, Length: 15411, dtype: int64

**Standard Scaler**

In [213]:
from sklearn.preprocessing import StandardScaler

In [214]:
scaler = StandardScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)

In [215]:
X_scaled.std()

vehicle_age          1.000032
km_driven            1.000032
seller_type          1.000032
fuel_type            1.000032
transmission_type    1.000032
mileage              1.000032
engine               1.000032
max_power            1.000032
seats                1.000032
dtype: float64

In [216]:
X_scaled.head()

,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,0.983562,1.247335,1.189966,-0.954505,-0.510503,-0.000276,-1.324259,-1.263352,-0.403022
1,-0.343933,-0.690016,1.189966,-0.954505,-0.510503,-0.192071,-0.554718,-0.432571,-0.403022
2,1.647309,0.084924,1.189966,-0.954505,-0.510503,-0.647583,-0.554718,-0.479113,-0.403022
3,0.983562,-0.360667,1.189966,-0.954505,-0.510503,0.292211,-0.936610,-0.779312,-0.403022
4,-0.012060,-0.496281,-0.768028,0.846190,-0.510503,0.735736,0.022918,-0.046502,-0.403022

In [217]:
X = X_scaled

In [218]:
X.head()

,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,0.983562,1.247335,1.189966,-0.954505,-0.510503,-0.000276,-1.324259,-1.263352,-0.403022
1,-0.343933,-0.690016,1.189966,-0.954505,-0.510503,-0.192071,-0.554718,-0.432571,-0.403022
2,1.647309,0.084924,1.189966,-0.954505,-0.510503,-0.647583,-0.554718,-0.479113,-0.403022
3,0.983562,-0.360667,1.189966,-0.954505,-0.510503,0.292211,-0.936610,-0.779312,-0.403022
4,-0.012060,-0.496281,-0.768028,0.846190,-0.510503,0.735736,0.022918,-0.046502,-0.403022

In [219]:
X.shape

(15411, 9)

**Train Test Split**

In [220]:
from sklearn.model_selection import train_test_split

In [221]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.25,random_state=2)

In [222]:
print(X.shape,X_train.shape,X_test.shape)

(15411, 9) (11558, 9) (3853, 9)

**Model Evaluation**

In [223]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [224]:
def evaluate(true,predicted):
  mae = mean_absolute_error(true,predicted)
  mse = mean_squared_error(true,predicted)
  r2 = r2_score(true,predicted)
  return mae,mse,r2

**Model Training**

In [225]:
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from xgboost import XGBRegressor

In [226]:
models = [LinearRegression(),Lasso(),Ridge(),DecisionTreeRegressor(),RandomForestRegressor(),KNeighborsRegressor(),SVR(),AdaBoostRegressor(),GradientBoostingRegressor(),XGBRegressor()]

In [227]:


for model in models:
  model.fit(X_train,Y_train)

  Y_train_pred = model.predict(X_train)
  Y_test_pred = model.predict(X_test)

  print("Model Name:",model)
  print()

  print("Training Results:")
  mae,mse,r2 = evaluate(Y_train,Y_train_pred)
  print("MAE:",mae)
  print("MSE:",mse)
  print("R2:",r2)

  print()

  print("Testing Result:")
  mae,mse,r2 = evaluate(Y_test,Y_test_pred)
  print("MAE:",mae)
  print("MSE:",mse)
  print("R2:",r2)

  print()
  print()

  print("-------------------------------------------------------------------------------------")

Model Name: LinearRegression()

Training Results:
MAE: 275652.5157960078
MSE: 327967189713.2624
R2: 0.612319634310311

Testing Result:
MAE: 263994.82046386605
MSE: 202298551288.05417
R2: 0.6933434145183182


-------------------------------------------------------------------------------------
Model Name: Lasso()

Training Results:
MAE: 275652.0009107509
MSE: 327967189723.7711
R2: 0.612319634297889

Testing Result:
MAE: 263994.3082053819
MSE: 202298451478.48965
R2: 0.6933435658157945


-------------------------------------------------------------------------------------
Model Name: Ridge()

Training Results:
MAE: 275632.86318343476
MSE: 327967203506.3299
R2: 0.6123196180059318

Testing Result:
MAE: 263973.7532855642
MSE: 202288935917.96307
R2: 0.6933579900876512


-------------------------------------------------------------------------------------
Model Name: DecisionTreeRegressor()

Training Results:
MAE: 4903.1876498652755
MSE: 398146519.62359613
R2: 0.9995293627132009

Testing Result:
MAE: 130857.6131153214
MSE: 235939145588.0699
R2: 0.6423489327687768


-------------------------------------------------------------------------------------
Model Name: RandomForestRegressor()

Training Results:
MAE: 41807.09970568884
MSE: 20001764819.58914
R2: 0.9763565022876924

Testing Result:
MAE: 98930.31267407507
MSE: 39707191813.50412
R2: 0.9398093966414164


-------------------------------------------------------------------------------------
Model Name: KNeighborsRegressor()

Training Results:
MAE: 99476.24805329641
MSE: 121810480061.59154
R2: 0.8560114153601728

Testing Result:
MAE: 115001.08357124319
MSE: 54773662564.39787
R2: 0.9169707136834255


-------------------------------------------------------------------------------------
Model Name: SVR()

Training Results:
MAE: 401891.29761048045
MSE: 892889163347.2073
R2: -0.055458009898627925

Testing Result:
MAE: 395724.56568466953
MSE: 702916934842.3392
R2: -0.06552471949773242


-------------------------------------------------------------------------------------
Model Name: AdaBoostRegressor()

Training Results:
MAE: 385737.8953432238
MSE: 263457386522.83783
R2: 0.6885747746897461

Testing Result:
MAE: 392721.2739353914
MSE: 287174966396.9251
R2: 0.564682524563892


-------------------------------------------------------------------------------------
Model Name: GradientBoostingRegressor()

Training Results:
MAE: 114946.30420298844
MSE: 45353455380.8937
R2: 0.9463890147586771

Testing Result:
MAE: 118847.94522087471
MSE: 65734201549.974304
R2: 0.9003560546116964


-------------------------------------------------------------------------------------
Model Name: XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

Training Results:
MAE: 65374.7578125
MSE: 8912063488.0
R2: 0.9894652962684631

Testing Result:
MAE: 103872.1484375
MSE: 143824584704.0
R2: 0.7819818258285522


-------------------------------------------------------------------------------------

Selected Models KNN,RF,Gradient

**HyperParameter Tuning**

In [228]:
# Hypermater Tuning
knn_params = {'n_neighbors': [2,3,10,20,40,50]}
rf_params = {
    "max_depth": [5, 8, 15, None, 10],
    "max_features": [5, 7, "sqrt", None],
    "min_samples_split": [2, 8, 15, 20],
    "n_estimators": [100, 200, 500, 1000]
}
# xg_params = {'learning_rate':[0.1,0.01],
#             'max_depth':[5,8,12,20,30],
#             'n_estimators':[100,200,300],
#             'colsample_bytree':[0.5,0.8,1,0.3,0.4]}

# gradient_params={
#     'loss': ['squared_error', 'absolute_error', 'huber', 'quantile'],
#     'criterion': ['friedman_mse', 'squared_error'],
#     'n_estimators': [100, 200, 500],
#     'max_depth': [5, 8, 15, None]
# }

# **Model Selection**

In [229]:
from sklearn.model_selection import RandomizedSearchCV

In [230]:
randomcv_models = [('RF', RandomForestRegressor(), rf_params),
                   ('KNN', KNeighborsRegressor(), knn_params)
                  ]

In [231]:
model_param = {}
for name, model, params in randomcv_models:
    print(f"\n🔍 Tuning {name}...")
    random = RandomizedSearchCV(
        estimator=model,
        param_distributions=params,
        n_iter=10,
        cv=2,
        verbose=2,
        n_jobs=-1,
        random_state=42
    )
    random.fit(X_train, Y_train)
    model_param[name] = random.best_params_, random.best_score_
    print(f"{name} has been successfully tuned.")

# Show best parameters
for model_name in model_param:
    print(f"\n-------------------- Best Params for {model_name} -------------------")
    print(model_param[model_name])

🔍 Tuning RF...
Fitting 2 folds for each of 10 candidates, totalling 20 fits
RF has been successfully tuned.

🔍 Tuning KNN...
Fitting 2 folds for each of 6 candidates, totalling 12 fits
KNN has been successfully tuned.

-------------------- Best Params for RF -------------------
({'n_estimators': 100, 'min_samples_split': 2, 'max_features': 'sqrt', 'max_depth': None}, np.float64(0.8248467924694145))

-------------------- Best Params for KNN -------------------
({'n_neighbors': 3}, np.float64(0.7820962455797346))

In [232]:
model = RandomForestRegressor(max_depth=None, max_features='sqrt', min_samples_split=2,
                       n_estimators=100, random_state=42)

In [233]:
print(model)

RandomForestRegressor(max_features='sqrt', random_state=42)

In [234]:
model.fit(X_train,Y_train)

Y_train_pred = model.predict(X_train)
Y_test_pred = model.predict(X_test)

print(r2_score(Y_train,Y_train_pred))
print(r2_score(Y_test,Y_test_pred))

0.9790985514058937
0.9417479310623975

In [235]:
new_customer_features = [[11, 60000, 1, 0, 0, 17.00, 1197, 80.00, 5]]
new_customer_scaled = scaler.transform(new_customer_features)
prediction = model.predict(new_customer_scaled)
print(f"Predicted price: ₹{prediction[0]:,.2f}")

Predicted price: ₹318,720.00

In [236]:
import pickle

In [237]:
filename = 'car_price_model.sav'
pickle.dump(model,open(filename,'wb'))

In [238]:
loaded_model = pickle.load(open(filename,'rb'))

In [239]:
filename = 'car_price_model.pkl'
pickle.dump(model,open(filename,'wb'))

In [240]:
loaded_model = pickle.load(open(filename,'rb'))

In [241]:
new_customer_features = [[11, 60000, 1, 0, 0, 17.00, 1197, 80.00, 5]]
new_customer_scaled = scaler.transform(new_customer_features)
prediction = loaded_model.predict(new_customer_scaled)
print(f"Predicted price: ₹{prediction[0]:,.2f}")

Predicted price: ₹318,720.00